### ISSUE TITLE
Awesome project, congratulations!

### ISSUE THREAD

**Issue by krother** [xettrisomeman/mlbootcamp#1]
Hi @xettrisomeman ,

this is a super clean, systematic approach and I found it great to see that the Nepalese character encoding worked.
For me, the most interesting part was the web app with FastAPI - this one went to my reading list.

Congrats to your midterm project!
     Kristian

**Comment by xettrisomeman** [comment]
Thank you very much :) I did create a library to tokenize nepali text :) I feel amazing that you loved my project :) :hugs: :hugs
